export const locales = ["de", "en"];
export const defaultLocale = "de";

export const dict = {
  de: {
    brandSub: "HYROX & Hybrid · Rennplan und Split-Analyse",
    tabPlan: "Rennplan",
    tabAnalyse: "Analyse",
    format: "Format",
    category: "Kategorie",
    men: "Herren", women: "Damen", mixed: "Mixed",
    run: "Lauf",
    targetLabel: "Zielzeit (h:mm:ss)",
    runnerStrong: "← läuferisch stark",
    stationStrong: "stationsstark →",
    biasHint: "verschiebt das Zeitbudget zwischen Laufen und Stationen",
    estTitle: "Zielzeit aus Laufzeit ableiten",
    optional: "(optional)",
    estHint: "Deine frische 5- oder 10-km-Zeit → geschätzte HYROX-Lauf-Pace und Zielzeit.",
    apply: "Übernehmen",
    runPh5: "z. B. 22:30", runPh10: "z. B. 47:00",
    freshPace: "Frische Pace:",
    fatigue: "Renn-Fatigue",
    hyroxPaceLabel: "HYROX-Pace:",
    targetArrow: "→ Zielzeit:",
    sumRun: "Laufen", sumStations: "Stationen", sumRoxzone: "Roxzone",
    copyPlan: "Plan kopieren", copied: "Kopiert",
    shareLink: "Teilbaren Link kopieren", linkCopied: "Link kopiert",
    downloadCard: "Race Card herunterladen",
    downloadStory: "Auch als Story (Hochformat)",
    shareShort: "Link", cardShort: "Karte", storyShort: "Story",
    share: "Teilen", planShort: "Plan",
    shareText: "Mein Rennplan – erstellt mit Hybrid Pacer",
    notAffiliated: "Nicht mit HYROX bzw. der HYROX GmbH verbunden oder von ihr unterstützt. HYROX ist eine eingetragene Marke der jeweiligen Inhaber.",
    install: "Installieren",
    installApp: "Hybrid Pacer als App installieren",
    iosInstall: "Installieren: unten auf das Teilen-Symbol tippen → „Zum Home-Bildschirm“.",
    brand: "HYBRIDSTATE",
    homeTagline: "Hör auf, deine Pace zu raten.",
    homeIntro: "Hybridstate baut die Tools, die dich im HYROX schneller machen – ehrlich gerechnet, kostenlos, ohne Anmeldung. Den Anfang macht der Hybrid Pacer: Zielzeit rein, fertiger Rennplan raus.",
    homeAvailable: "Schon verfügbar",
    homeComing: "Kommt bald",
    pacerName: "Hybrid Pacer",
    pacerDesc: "Zielzeit eingeben → fertiger Rennplan: Pace für jeden Lauf, Zeit für jede Station, Roxzone-Puffer. Im Analyse-Modus trägst du deine echten Splits ein und siehst sofort, wo die meiste Zeit liegen bleibt.",
    openPacer: "Pacer öffnen",
    heroCta: "Rennplan erstellen",
    planName: "Trainingsplan",
    planDesc: "Ein Plan, der dich Woche für Woche zum Renntag bringt – abgestimmt auf Format, Level und Zielzeit.",
    fuelName: "Race-Week Fueling",
    fuelDesc: "Was, wann, wie viel: Carb-Loading, Hydration und Verpflegung für Rennwoche und Renntag.",
    appName: "iPhone-App",
    appDesc: "Der Pacer in der Tasche – griffbereit auf jeder Trainingsfläche.",
    notifyTitle: "Sei dabei, sobald die Trainingspläne live gehen.",
    notifyDesc: "Eine Mail, wenn's so weit ist – sonst nichts. Jederzeit abbestellbar.",
    notifyPlaceholder: "Deine E-Mail-Adresse",
    notifyBtn: "Benachrichtige mich",
    notifySending: "Senden…",
    notifyConsentPre: "Mit dem Eintragen stimmst du zu, gelegentlich E-Mails von Hybridstate zu erhalten. Mehr in der ",
    notifyConsentLink: "Datenschutzerklärung",
    notifyOk: "Fast geschafft! Bitte bestätige den Link in deiner E-Mail.",
    notifyErr: "Das hat nicht geklappt. Bitte prüfe deine E-Mail-Adresse.",
    notifyUnconfigured: "Die Anmeldung ist noch nicht aktiv – schau bald wieder vorbei.",
    backHome: "Hybridstate",
    disclaimer: "Hybrid Pacer ist ein unabhängiges Tool und steht in keiner Verbindung zu HYROX bzw. der HYROX GmbH und wird von dieser nicht unterstützt. HYROX ist eine Marke ihrer jeweiligen Inhaber.",
    emailTitle: "Plan per Mail schicken",
    emailTitleAnalysis: "Analyse per Mail schicken",
    analysisSubject: "Deine HYROX-Analyse",
    analysisHeading: "Deine HYROX-Analyse",
    contribTitle: "Ergebnis beitragen",
    contribHint: "Teile deine eingetragenen Zeiten anonym, um das Modell für alle zu verbessern.",
    contribBtn: "Anonym beitragen",
    contribThanks: "Danke! Dein Ergebnis ist gespeichert.",
    contribFail: "Konnte nicht gespeichert werden.",
    basedOnPre: "Basierend auf ",
    basedOnPost: " echten Ergebnissen",
    compareSrc: "Vergleich mit:",
    srcModel: "Modell",
    srcCommunity: "Community",
    emailPlaceholder: "deine@email.de",
    send: "Senden",
    consent: "Schick mir außerdem gelegentlich Tipps & Updates (Double-Opt-in, jederzeit abbestellbar).",
    emailNotePre: "Du bekommst deinen angeforderten Rennplan zugeschickt. Mehr in der ",
    privacy: "Datenschutzerklärung",
    invalidTarget: "Bitte eine gültige Zielzeit eingeben, z. B. 1:15:00 oder 75:00.",
    sentOk: "Plan ist unterwegs ✓",
    sentOkOptin: "Plan ist unterwegs ✓ Bitte bestätige zusätzlich die Newsletter-Anmeldung in deiner Mail.",
    sendFail: "Versand fehlgeschlagen.",
    netErr: "Netzwerkfehler.",
    invalidEmail: "Bitte eine gültige E-Mail eingeben.",
    analyseHint: "Trag deine echten Zeiten ein (vorausgefüllt mit dem Durchschnitt deiner Kategorie). Unten siehst du deine Prognose und wo du die meiste Zeit verlierst.",
    roxTotal: "Roxzone gesamt",
    compareTarget: "Vergleichs-Zielzeit",
    predicted: "Prognostizierte Endzeit",
    under: "unter", over: "über", targetBy: "Zielzeit um",
    biggestLosses: "Größte Zeitverluste",
    deviation: "Abweichung pro Element",
    chartNote: "Coral = langsamer als die Vergleichszeit (Zeitverlust), Blau = schneller. Größter Coral-Balken = dein bester Hebel.",
    fillAll: "Bitte alle Felder im Format mm:ss ausfüllen.",
    nextStep: "Nächster Schritt (geplant):",
    membership: "Willst du statt der Schätzung einen individuellen Plan, der sich an dein Training anpasst? Hier kommt später die Anmeldung zur Membership.",
    planSubject: "Dein HYROX-Rennplan",
    seoH2: "HYROX Rechner: Rennplan und Split-Analyse",
    seoP1: "Der Hybrid Pacer rechnet deine HYROX-Zielzeit in einen konkreten Rennplan um – mit Ziel-Pace für jeden der acht 1-km-Läufe, Ziel-Zeiten für alle acht Stationen und einem Puffer für die Roxzone. Im Analyse-Modus trägst du deine echten Zeiten ein und siehst, wo du im Vergleich zur Zielzeit die meiste Zeit verlierst.",
    seoQ1: "Welche HYROX-Zeit ist mit meiner 5-km- oder 10-km-Zeit realistisch?",
    seoA1: "Im Rennen läufst du nicht frisch: Durch Stationen und Ermüdung liegt deine HYROX-Lauf-Pace meist 30–60 Sekunden pro Kilometer über deiner frischen Pace. Gib deine 5- oder 10-km-Zeit ein, und das Tool schätzt daraus eine realistische Zielzeit.",
    seoQ2: "Open, Pro oder Doubles?",
    seoA2: "Alle Formate sind wählbar. Pro nutzt schwerere Lasten; Doubles wird durch das Teilen der Stationen schneller. Die Werte sind fundierte Richtwerte und kein offizieller Wettkampf-Standard.",
    langName: "DE",
  },
  en: {
    brandSub: "HYROX & Hybrid · Race plan & split analysis",
    tabPlan: "Race plan",
    tabAnalyse: "Analysis",
    format: "Format",
    category: "Category",
    men: "Men", women: "Women", mixed: "Mixed",
    run: "Run",
    targetLabel: "Target time (h:mm:ss)",
    runnerStrong: "← runner-strong",
    stationStrong: "station-strong →",
    biasHint: "shifts the time budget between running and stations",
    estTitle: "Estimate target from a run time",
    optional: "(optional)",
    estHint: "Your fresh 5K or 10K time → estimated HYROX run pace and target.",
    apply: "Apply",
    runPh5: "e.g. 22:30", runPh10: "e.g. 47:00",
    freshPace: "Fresh pace:",
    fatigue: "race fatigue",
    hyroxPaceLabel: "HYROX pace:",
    targetArrow: "→ Target:",
    sumRun: "Running", sumStations: "Stations", sumRoxzone: "Roxzone",
    copyPlan: "Copy plan", copied: "Copied",
    shareLink: "Copy shareable link", linkCopied: "Link copied",
    downloadCard: "Download race card",
    downloadStory: "Also as a story (portrait)",
    shareShort: "Link", cardShort: "Card", storyShort: "Story",
    share: "Share", planShort: "Plan",
    shareText: "My race plan – made with Hybrid Pacer",
    notAffiliated: "Not affiliated with or endorsed by HYROX. HYROX is a trademark of its respective owners.",
    install: "Install",
    installApp: "Install Hybrid Pacer as an app",
    iosInstall: "Install: tap the Share icon → “Add to Home Screen”.",
    brand: "HYBRIDSTATE",
    homeTagline: "Stop guessing your pace.",
    homeIntro: "Hybridstate builds the tools that make you faster at HYROX – honestly calculated, free, no sign-up. It starts with the Hybrid Pacer: enter your target time, get a full race plan.",
    homeAvailable: "Available now",
    homeComing: "Coming soon",
    pacerName: "Hybrid Pacer",
    pacerDesc: "Enter your target time → a full race plan: pace for every run, time for every station, roxzone buffer. In analysis mode, enter your real splits and instantly see where you lose the most time.",
    openPacer: "Open the Pacer",
    heroCta: "Build my race plan",
    planName: "Training plan",
    planDesc: "A plan that takes you to race day, week by week – tuned to your format, level and target time.",
    fuelName: "Race-week fueling",
    fuelDesc: "What, when, how much: carb-loading, hydration and fueling for race week and race day.",
    appName: "iPhone app",
    appDesc: "The Pacer in your pocket – ready on any training floor.",
    notifyTitle: "Be there when training plans launch.",
    notifyDesc: "One email when it's ready – nothing else. Unsubscribe anytime.",
    notifyPlaceholder: "Your email address",
    notifyBtn: "Notify me",
    notifySending: "Sending…",
    notifyConsentPre: "By signing up you agree to receive occasional emails from Hybridstate. See our ",
    notifyConsentLink: "privacy policy",
    notifyOk: "Almost there! Please confirm the link in your email.",
    notifyErr: "That didn't work. Please check your email address.",
    notifyUnconfigured: "Sign-up isn't active yet – check back soon.",
    backHome: "Hybridstate",
    emailTitle: "Email me the plan",
    emailTitleAnalysis: "Email me the analysis",
    analysisSubject: "Your HYROX analysis",
    analysisHeading: "Your HYROX analysis",
    contribTitle: "Contribute your result",
    contribHint: "Share your entered times anonymously to improve the model for everyone.",
    contribBtn: "Contribute anonymously",
    contribThanks: "Thanks! Your result is saved.",
    contribFail: "Could not be saved.",
    basedOnPre: "Based on ",
    basedOnPost: " real results",
    compareSrc: "Compare to:",
    srcModel: "Model",
    srcCommunity: "Community",
    emailPlaceholder: "you@email.com",
    send: "Send",
    consent: "Also send me occasional tips & updates (double opt-in, unsubscribe anytime).",
    emailNotePre: "You'll receive the race plan you requested. More in the ",
    privacy: "privacy policy",
    invalidTarget: "Please enter a valid target time, e.g. 1:15:00 or 75:00.",
    sentOk: "Plan is on its way ✓",
    sentOkOptin: "Plan is on its way ✓ Please also confirm the newsletter sign-up in your inbox.",
    sendFail: "Sending failed.",
    netErr: "Network error.",
    invalidEmail: "Please enter a valid email.",
    analyseHint: "Enter your real times (pre-filled with your category average). Below you'll see your predicted finish and where you lose the most time.",
    roxTotal: "Roxzone total",
    compareTarget: "Comparison target",
    predicted: "Predicted finish",
    under: "under", over: "over", targetBy: "target by",
    biggestLosses: "Biggest time losses",
    deviation: "Deviation per element",
    chartNote: "Coral = slower than the comparison (time lost), blue = faster. Biggest coral bar = your best lever.",
    fillAll: "Please fill all fields as mm:ss.",
    nextStep: "Next step (planned):",
    membership: "Want a personalized plan that adapts to your training instead of the estimate? The membership sign-up will live here.",
    planSubject: "Your HYROX race plan",
    seoH2: "HYROX calculator: race plan & split analysis",
    seoP1: "Hybrid Pacer turns your HYROX target time into a concrete race plan – target pace for each of the eight 1 km runs, target times for all eight stations and a buffer for the roxzone. In analysis mode you enter your real times and see where you lose the most time versus your target.",
    seoQ1: "What HYROX time is realistic from my 5K or 10K?",
    seoA1: "You don't run fresh in a race: with stations and fatigue your HYROX run pace is usually 30–60 seconds per kilometre slower than your fresh pace. Enter your 5K or 10K time and the tool estimates a realistic target.",
    seoQ2: "Open, Pro or Doubles?",
    seoA2: "All formats are selectable. Pro uses heavier loads; Doubles is faster because stations are shared. Values are informed estimates, not an official competition standard.",
    langName: "EN",
  },
};
